### 获取 token
POST 127.0.0.1:8100/ecommerce-sentinel-client/sentinel-fallback/get-token
Content-Type: application/json

{
  "username": "Qinyi@imooc.com",
  "password": "25d55ad283aa400af464c76d713c07ad"
}

### 忽略异常
GET 127.0.0.1:8100/ecommerce-sentinel-client/sentinel-fallback/ignore-exception?code=2
Content-Type: application/json
