### 获取 Token
POST http://127.0.0.1:9001/caostudy/ecommerce-nacos-client/communication/token-by-feign
Content-Type: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcIkNhb1N0dWR5QGltb29jLmNvbVwifSIsImp0aSI6ImQ5MTZhZTJlLTUwNGYtNDk1MS1iNzcwLTg5NmNhYTFlNzE4ZiIsImV4cCI6MTYzMjQ5OTIwMH0.Vg0ZrviFB49w4Z6Hu2ZFiGiwxY_x0nrj7BDgfSCvl_iZ6x5AiYPDQqfYEAr3usITJGRDXogtuQRukTfXV2-yy2BwGDFcfDIiaTKRSf7OsHDH5kZFqFEyULwedWlDHfXl3liTzzc49yoUAWmq19tcpLN8FmeOGtNSCBn_BA2t1iUxjeTC7rLm4wPTEL1rwlRwAgZxze3LPLvWLcevqL3qZU2N84YtlDOFkk8K613ah2JQzcnmDYghnLiTdqSu7OYOjTmMx4In80ccCDwFKCWjysXTEHSgPD9XGlE09ySamlJAb_W2QtiJW62Ob5l27qLK0A_4Tgv5EpyWVmIr0GIeMA
token: caostudy

{
  "username": "CaoStudy@imooc.com",
  "password": "25d55ad283aa400af464c76d713c07ad"
}


### 根据提供的 serviceId 获取实例信息
GET http://127.0.0.1:9001/caostudy/ecommerce-nacos-client/hystrix/hystrix-command-annotation?serviceId=e-commerce-nacos-client
Content-Type: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcIkNhb1N0dWR5QGltb29jLmNvbVwifSIsImp0aSI6ImQ5MTZhZTJlLTUwNGYtNDk1MS1iNzcwLTg5NmNhYTFlNzE4ZiIsImV4cCI6MTYzMjQ5OTIwMH0.Vg0ZrviFB49w4Z6Hu2ZFiGiwxY_x0nrj7BDgfSCvl_iZ6x5AiYPDQqfYEAr3usITJGRDXogtuQRukTfXV2-yy2BwGDFcfDIiaTKRSf7OsHDH5kZFqFEyULwedWlDHfXl3liTzzc49yoUAWmq19tcpLN8FmeOGtNSCBn_BA2t1iUxjeTC7rLm4wPTEL1rwlRwAgZxze3LPLvWLcevqL3qZU2N84YtlDOFkk8K613ah2JQzcnmDYghnLiTdqSu7OYOjTmMx4In80ccCDwFKCWjysXTEHSgPD9XGlE09ySamlJAb_W2QtiJW62Ob5l27qLK0A_4Tgv5EpyWVmIr0GIeMA
token: caostudy


### 根据提供的 serviceId 获取实例信息
GET http://127.0.0.1:9001/caostudy/ecommerce-nacos-client/hystrix/simple-hystrix-command?serviceId=e-commerce-nacos-client
Content-Type: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcIkNhb1N0dWR5QGltb29jLmNvbVwifSIsImp0aSI6ImQ5MTZhZTJlLTUwNGYtNDk1MS1iNzcwLTg5NmNhYTFlNzE4ZiIsImV4cCI6MTYzMjQ5OTIwMH0.Vg0ZrviFB49w4Z6Hu2ZFiGiwxY_x0nrj7BDgfSCvl_iZ6x5AiYPDQqfYEAr3usITJGRDXogtuQRukTfXV2-yy2BwGDFcfDIiaTKRSf7OsHDH5kZFqFEyULwedWlDHfXl3liTzzc49yoUAWmq19tcpLN8FmeOGtNSCBn_BA2t1iUxjeTC7rLm4wPTEL1rwlRwAgZxze3LPLvWLcevqL3qZU2N84YtlDOFkk8K613ah2JQzcnmDYghnLiTdqSu7OYOjTmMx4In80ccCDwFKCWjysXTEHSgPD9XGlE09ySamlJAb_W2QtiJW62Ob5l27qLK0A_4Tgv5EpyWVmIr0GIeMA
token: caostudy


### 根据提供的 serviceId 获取实例信息
GET http://127.0.0.1:9001/caostudy/ecommerce-nacos-client/hystrix/hystrix-observable-command?serviceId=e-commerce-nacos-client
Content-Type: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcIkNhb1N0dWR5QGltb29jLmNvbVwifSIsImp0aSI6ImQ5MTZhZTJlLTUwNGYtNDk1MS1iNzcwLTg5NmNhYTFlNzE4ZiIsImV4cCI6MTYzMjQ5OTIwMH0.Vg0ZrviFB49w4Z6Hu2ZFiGiwxY_x0nrj7BDgfSCvl_iZ6x5AiYPDQqfYEAr3usITJGRDXogtuQRukTfXV2-yy2BwGDFcfDIiaTKRSf7OsHDH5kZFqFEyULwedWlDHfXl3liTzzc49yoUAWmq19tcpLN8FmeOGtNSCBn_BA2t1iUxjeTC7rLm4wPTEL1rwlRwAgZxze3LPLvWLcevqL3qZU2N84YtlDOFkk8K613ah2JQzcnmDYghnLiTdqSu7OYOjTmMx4In80ccCDwFKCWjysXTEHSgPD9XGlE09ySamlJAb_W2QtiJW62Ob5l27qLK0A_4Tgv5EpyWVmIr0GIeMA
token: caostudy
