### 查询服务
GET http://127.0.0.1:9001/caostudy/ecommerce-nacos-client/nacos-client/service-instance?serviceId=e-commerce-gateway
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEyLFwidXNlcm5hbWVcIjpcIkltb29jUWlueWlAaW1vb2MuY29tXCJ9IiwianRpIjoiZmQ4MDdkOTktNThjNC00NmMyLTg4NGMtOGVlNGM0OGYyYTVhIiwiZXhwIjoxNjMyMDY3MjAwfQ.GrMBC0JKd_Faa0AtO6LMgv8yHKh9dplnCn-RXjHUBCI9tsPhk3yEWvXKd7fueBQQLtruAHydoKCxwNO-LyEAo_qK6WI7mgffpnhpqMRQ-DDMLL_Cbp2ZQlZnaJMkkhNNrmDgRESfdUY2LOvavl0wHJPZvqEG_Z9AWXmrL3axlsgoiTN3ni2rSnJ7E08DubzdTHNjKY4OwMdQP5vDZk9467KbFWxOakyP6_MymBkUhg7p7Sfc-I2XdMJtzVZt18nmYfszAQO1mGlxoxgRdMMAWoK3ISj52L5DkEttgCOLh7pWMtTyGqPvQpMWQAAB3vBJqpPC270FqM_QrnsSkY01Wg
token: caostudy